version: "3.9"
services:
  cloud_function:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./main.py:/app/main.py
      - ./{{ cookiecutter.project_slug }}:/app/{{ cookiecutter.project_slug }}
    # secrets:
    #   - google_creds
    environment:
      - LOG_LEVEL=${LOG_LEVEL}

# secrets:
#   google_creds:
#     file: $GOOGLE_APPLICATION_CREDENTIALS
